---
title: "Transmission with group structure"
author: "Juan S. Vargas"
format: html
editor: visual
---

In the simple SIR model with environmental transmission from carcasses, the transmission process is modelled as $\beta S D$, where $S$ is the density of susceptible individuals in the population, $D$ is the density of (infectious) carcasses on the landscape, and $\beta$ is a search parameter with units Area/time. However, the group structure of musk oxen and caribou could generate heterogeneity in transmission processes. When one individual encounters a carcass, there is a high likelihood that other individuals are nearby, and that they too will come into contact with the carcass and contaminated soil around it. Thus, we cannot assume homogeneous mixing, we have to check what the transmission function would look like.

We can conceptualize the transmission process as follows: A given group of animals covers a certain area $A_x$ over a period $\Delta t$. Depending on the density of carcasses on the landscape, and assuming carcasses are uniformly distributed, there will be a certain number of carcasses in $A_x$. Every individual in the group has the same probability of coming into contact with these. Each contact is considered independent, and each one may lead to infection. This infection process has to be integrated across individuals in a group, and furthermore across groups in the population. We have:

$$
\begin{align}
I(\Delta t)&=\sum_j^H{\sum_i^N{\nu_j(x, \Delta t)\kappa_i(\nu_j)\delta_i\gamma(\kappa_i)}}\\
\end{align}
$$

In this equation, $\delta_i$ is an indicator function (0/1) showing whether individual $i$ is infected, $\gamma(\kappa)$ is the probability of infection for a susceptible individual, following a certain number of contacts with infectious material. The term $\kappa(\nu)$ is the number of contacts with infectious material on the landscape for a given individual, which depends on the number of carcasses around. The number of available carcasses is a function of the location of each herd, $x_j$, and the search period $\Delta t$. Here, $N$ is the number of individuals in a given group, and $H$ is the number of groups in the population.

Assuming a homogeneous distribution of carcasses, we have $\nu_j(x, \Delta t)=A(x,\Delta t) D$, *i.e.* the number of carcasses near the group is the density of carcasses on the landscape multiplied by the area available to the group, centered around a point $x$, during a period $\Delta t$. For simplicity, we assume for now that this area is constant regardless of group size, and that each individual encounter all carcasses within the group's search area. The infection process is modelled as:
